//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  post: Post;
  postConnection: PostConnection;
  page: Page;
  pageConnection: PageConnection;
  announcement: Announcement;
  announcementConnection: AnnouncementConnection;
  token: Token;
  tokenConnection: TokenConnection;
  landingPage: LandingPage;
  landingPageConnection: LandingPageConnection;
  footer: Footer;
  footerConnection: FooterConnection;
  publicPage: PublicPage;
  publicPageConnection: PublicPageConnection;
  faq: Faq;
  faqConnection: FaqConnection;
  pricing: Pricing;
  pricingConnection: PricingConnection;
  contact: Contact;
  contactConnection: ContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryAnnouncementArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAnnouncementConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AnnouncementFilter>;
};


export type QueryTokenArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTokenConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TokenFilter>;
};


export type QueryLandingPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLandingPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LandingPageFilter>;
};


export type QueryFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
};


export type QueryPublicPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPublicPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicPageFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};


export type QueryPricingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPricingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};

export type DocumentFilter = {
  post?: InputMaybe<PostFilter>;
  page?: InputMaybe<PageFilter>;
  announcement?: InputMaybe<AnnouncementFilter>;
  token?: InputMaybe<TokenFilter>;
  landingPage?: InputMaybe<LandingPageFilter>;
  footer?: InputMaybe<FooterFilter>;
  publicPage?: InputMaybe<PublicPageFilter>;
  faq?: InputMaybe<FaqFilter>;
  pricing?: InputMaybe<PricingFilter>;
  contact?: InputMaybe<ContactFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Post | Page | Announcement | Token | LandingPage | Footer | PublicPage | Faq | Pricing | Contact | Folder;

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  heroImg?: Maybe<Scalars['String']['output']>;
  date: Scalars['String']['output'];
  author: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  heroImg?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Announcement = Node & Document & {
  __typename?: 'Announcement';
  title: Scalars['String']['output'];
  message: Scalars['String']['output'];
  startDate: Scalars['String']['output'];
  endDate?: Maybe<Scalars['String']['output']>;
  active: Scalars['Boolean']['output'];
  type: Scalars['String']['output'];
  link?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AnnouncementFilter = {
  title?: InputMaybe<StringFilter>;
  message?: InputMaybe<StringFilter>;
  startDate?: InputMaybe<DatetimeFilter>;
  endDate?: InputMaybe<DatetimeFilter>;
  active?: InputMaybe<BooleanFilter>;
  type?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type AnnouncementConnectionEdges = {
  __typename?: 'AnnouncementConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Announcement>;
};

export type AnnouncementConnection = Connection & {
  __typename?: 'AnnouncementConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AnnouncementConnectionEdges>>>;
};

export type Token = Node & Document & {
  __typename?: 'Token';
  name: Scalars['String']['output'];
  symbol: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  logo: Scalars['String']['output'];
  contractAddress: Scalars['String']['output'];
  chain: Scalars['String']['output'];
  website?: Maybe<Scalars['String']['output']>;
  twitter?: Maybe<Scalars['String']['output']>;
  telegram?: Maybe<Scalars['String']['output']>;
  featured: Scalars['Boolean']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TokenFilter = {
  name?: InputMaybe<StringFilter>;
  symbol?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  contractAddress?: InputMaybe<StringFilter>;
  chain?: InputMaybe<StringFilter>;
  website?: InputMaybe<StringFilter>;
  twitter?: InputMaybe<StringFilter>;
  telegram?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TokenConnectionEdges = {
  __typename?: 'TokenConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Token>;
};

export type TokenConnection = Connection & {
  __typename?: 'TokenConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TokenConnectionEdges>>>;
};

export type LandingPageHero = {
  __typename?: 'LandingPageHero';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  ctaText: Scalars['String']['output'];
  ctaLink: Scalars['String']['output'];
  backgroundImage?: Maybe<Scalars['String']['output']>;
};

export type LandingPageFeaturesItems = {
  __typename?: 'LandingPageFeaturesItems';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type LandingPageFeatures = {
  __typename?: 'LandingPageFeatures';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<LandingPageFeaturesItems>>>;
};

export type LandingPageStatsItems = {
  __typename?: 'LandingPageStatsItems';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type LandingPageStats = {
  __typename?: 'LandingPageStats';
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<LandingPageStatsItems>>>;
};

export type LandingPageTestimonialsItems = {
  __typename?: 'LandingPageTestimonialsItems';
  quote: Scalars['String']['output'];
  author: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
};

export type LandingPageTestimonials = {
  __typename?: 'LandingPageTestimonials';
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<LandingPageTestimonialsItems>>>;
};

export type LandingPage = Node & Document & {
  __typename?: 'LandingPage';
  hero?: Maybe<LandingPageHero>;
  features?: Maybe<LandingPageFeatures>;
  stats?: Maybe<LandingPageStats>;
  testimonials?: Maybe<LandingPageTestimonials>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LandingPageHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
};

export type LandingPageFeaturesItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type LandingPageFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  items?: InputMaybe<LandingPageFeaturesItemsFilter>;
};

export type LandingPageStatsItemsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type LandingPageStatsFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<LandingPageStatsItemsFilter>;
};

export type LandingPageTestimonialsItemsFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
};

export type LandingPageTestimonialsFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<LandingPageTestimonialsItemsFilter>;
};

export type LandingPageFilter = {
  hero?: InputMaybe<LandingPageHeroFilter>;
  features?: InputMaybe<LandingPageFeaturesFilter>;
  stats?: InputMaybe<LandingPageStatsFilter>;
  testimonials?: InputMaybe<LandingPageTestimonialsFilter>;
};

export type LandingPageConnectionEdges = {
  __typename?: 'LandingPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<LandingPage>;
};

export type LandingPageConnection = Connection & {
  __typename?: 'LandingPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LandingPageConnectionEdges>>>;
};

export type FooterBranding = {
  __typename?: 'FooterBranding';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
};

export type FooterLinksSectionsItems = {
  __typename?: 'FooterLinksSectionsItems';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
  external?: Maybe<Scalars['Boolean']['output']>;
};

export type FooterLinksSections = {
  __typename?: 'FooterLinksSections';
  title: Scalars['String']['output'];
  items?: Maybe<Array<Maybe<FooterLinksSectionsItems>>>;
};

export type FooterLinks = {
  __typename?: 'FooterLinks';
  sections?: Maybe<Array<Maybe<FooterLinksSections>>>;
};

export type FooterSocialPlatforms = {
  __typename?: 'FooterSocialPlatforms';
  twitter?: Maybe<Scalars['String']['output']>;
  discord?: Maybe<Scalars['String']['output']>;
  telegram?: Maybe<Scalars['String']['output']>;
  youtube?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  github?: Maybe<Scalars['String']['output']>;
};

export type FooterSocial = {
  __typename?: 'FooterSocial';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  platforms?: Maybe<FooterSocialPlatforms>;
};

export type FooterNewsletter = {
  __typename?: 'FooterNewsletter';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  placeholder?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
};

export type FooterLegalLinks = {
  __typename?: 'FooterLegalLinks';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type FooterLegal = {
  __typename?: 'FooterLegal';
  copyright?: Maybe<Scalars['String']['output']>;
  disclaimer?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<FooterLegalLinks>>>;
};

export type Footer = Node & Document & {
  __typename?: 'Footer';
  branding?: Maybe<FooterBranding>;
  links?: Maybe<FooterLinks>;
  social?: Maybe<FooterSocial>;
  newsletter?: Maybe<FooterNewsletter>;
  legal?: Maybe<FooterLegal>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FooterBrandingFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
};

export type FooterLinksSectionsItemsFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  external?: InputMaybe<BooleanFilter>;
};

export type FooterLinksSectionsFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<FooterLinksSectionsItemsFilter>;
};

export type FooterLinksFilter = {
  sections?: InputMaybe<FooterLinksSectionsFilter>;
};

export type FooterSocialPlatformsFilter = {
  twitter?: InputMaybe<StringFilter>;
  discord?: InputMaybe<StringFilter>;
  telegram?: InputMaybe<StringFilter>;
  youtube?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  github?: InputMaybe<StringFilter>;
};

export type FooterSocialFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  platforms?: InputMaybe<FooterSocialPlatformsFilter>;
};

export type FooterNewsletterFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
};

export type FooterLegalLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type FooterLegalFilter = {
  copyright?: InputMaybe<StringFilter>;
  disclaimer?: InputMaybe<StringFilter>;
  links?: InputMaybe<FooterLegalLinksFilter>;
};

export type FooterFilter = {
  branding?: InputMaybe<FooterBrandingFilter>;
  links?: InputMaybe<FooterLinksFilter>;
  social?: InputMaybe<FooterSocialFilter>;
  newsletter?: InputMaybe<FooterNewsletterFilter>;
  legal?: InputMaybe<FooterLegalFilter>;
};

export type FooterConnectionEdges = {
  __typename?: 'FooterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Footer>;
};

export type FooterConnection = Connection & {
  __typename?: 'FooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FooterConnectionEdges>>>;
};

export type PublicPageHero = {
  __typename?: 'PublicPageHero';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
};

export type PublicPageSeo = {
  __typename?: 'PublicPageSeo';
  metaTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Scalars['String']['output']>;
  ogImage?: Maybe<Scalars['String']['output']>;
};

export type PublicPage = Node & Document & {
  __typename?: 'PublicPage';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<PublicPageHero>;
  content?: Maybe<Scalars['JSON']['output']>;
  seo?: Maybe<PublicPageSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PublicPageHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
};

export type PublicPageSeoFilter = {
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<ImageFilter>;
};

export type PublicPageFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  hero?: InputMaybe<PublicPageHeroFilter>;
  content?: InputMaybe<RichTextFilter>;
  seo?: InputMaybe<PublicPageSeoFilter>;
};

export type PublicPageConnectionEdges = {
  __typename?: 'PublicPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PublicPage>;
};

export type PublicPageConnection = Connection & {
  __typename?: 'PublicPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PublicPageConnectionEdges>>>;
};

export type FaqCategoriesQuestions = {
  __typename?: 'FaqCategoriesQuestions';
  question: Scalars['String']['output'];
  answer: Scalars['JSON']['output'];
  tags?: Maybe<Scalars['String']['output']>;
};

export type FaqCategories = {
  __typename?: 'FaqCategories';
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  questions?: Maybe<Array<Maybe<FaqCategoriesQuestions>>>;
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  categories?: Maybe<Array<Maybe<FaqCategories>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqCategoriesQuestionsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<RichTextFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type FaqCategoriesFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  questions?: InputMaybe<FaqCategoriesQuestionsFilter>;
};

export type FaqFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  categories?: InputMaybe<FaqCategoriesFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type PricingHero = {
  __typename?: 'PricingHero';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type PricingPlans = {
  __typename?: 'PricingPlans';
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  price: Scalars['String']['output'];
  period?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  popular?: Maybe<Scalars['Boolean']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
};

export type Pricing = Node & Document & {
  __typename?: 'Pricing';
  hero?: Maybe<PricingHero>;
  plans?: Maybe<Array<Maybe<PricingPlans>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PricingHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type PricingPlansFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
  popular?: InputMaybe<BooleanFilter>;
  badge?: InputMaybe<StringFilter>;
};

export type PricingFilter = {
  hero?: InputMaybe<PricingHeroFilter>;
  plans?: InputMaybe<PricingPlansFilter>;
};

export type PricingConnectionEdges = {
  __typename?: 'PricingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pricing>;
};

export type PricingConnection = Connection & {
  __typename?: 'PricingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PricingConnectionEdges>>>;
};

export type ContactHero = {
  __typename?: 'ContactHero';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type ContactContactInfo = {
  __typename?: 'ContactContactInfo';
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  businessHours?: Maybe<Scalars['String']['output']>;
};

export type ContactForm = {
  __typename?: 'ContactForm';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  submitText?: Maybe<Scalars['String']['output']>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  hero?: Maybe<ContactHero>;
  contactInfo?: Maybe<ContactContactInfo>;
  form?: Maybe<ContactForm>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type ContactContactInfoFilter = {
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  businessHours?: InputMaybe<StringFilter>;
};

export type ContactFormFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  submitText?: InputMaybe<StringFilter>;
};

export type ContactFilter = {
  hero?: InputMaybe<ContactHeroFilter>;
  contactInfo?: InputMaybe<ContactContactInfoFilter>;
  form?: InputMaybe<ContactFormFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePost: Post;
  createPost: Post;
  updatePage: Page;
  createPage: Page;
  updateAnnouncement: Announcement;
  createAnnouncement: Announcement;
  updateToken: Token;
  createToken: Token;
  updateLandingPage: LandingPage;
  createLandingPage: LandingPage;
  updateFooter: Footer;
  createFooter: Footer;
  updatePublicPage: PublicPage;
  createPublicPage: PublicPage;
  updateFaq: Faq;
  createFaq: Faq;
  updatePricing: Pricing;
  createPricing: Pricing;
  updateContact: Contact;
  createContact: Contact;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateAnnouncementArgs = {
  relativePath: Scalars['String']['input'];
  params: AnnouncementMutation;
};


export type MutationCreateAnnouncementArgs = {
  relativePath: Scalars['String']['input'];
  params: AnnouncementMutation;
};


export type MutationUpdateTokenArgs = {
  relativePath: Scalars['String']['input'];
  params: TokenMutation;
};


export type MutationCreateTokenArgs = {
  relativePath: Scalars['String']['input'];
  params: TokenMutation;
};


export type MutationUpdateLandingPageArgs = {
  relativePath: Scalars['String']['input'];
  params: LandingPageMutation;
};


export type MutationCreateLandingPageArgs = {
  relativePath: Scalars['String']['input'];
  params: LandingPageMutation;
};


export type MutationUpdateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationCreateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationUpdatePublicPageArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicPageMutation;
};


export type MutationCreatePublicPageArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicPageMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationUpdatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};


export type MutationCreatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};

export type DocumentUpdateMutation = {
  post?: InputMaybe<PostMutation>;
  page?: InputMaybe<PageMutation>;
  announcement?: InputMaybe<AnnouncementMutation>;
  token?: InputMaybe<TokenMutation>;
  landingPage?: InputMaybe<LandingPageMutation>;
  footer?: InputMaybe<FooterMutation>;
  publicPage?: InputMaybe<PublicPageMutation>;
  faq?: InputMaybe<FaqMutation>;
  pricing?: InputMaybe<PricingMutation>;
  contact?: InputMaybe<ContactMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  post?: InputMaybe<PostMutation>;
  page?: InputMaybe<PageMutation>;
  announcement?: InputMaybe<AnnouncementMutation>;
  token?: InputMaybe<TokenMutation>;
  landingPage?: InputMaybe<LandingPageMutation>;
  footer?: InputMaybe<FooterMutation>;
  publicPage?: InputMaybe<PublicPageMutation>;
  faq?: InputMaybe<FaqMutation>;
  pricing?: InputMaybe<PricingMutation>;
  contact?: InputMaybe<ContactMutation>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  heroImg?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AnnouncementMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  startDate?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['String']['input']>;
  active?: InputMaybe<Scalars['Boolean']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type TokenMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  symbol?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  contractAddress?: InputMaybe<Scalars['String']['input']>;
  chain?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  twitter?: InputMaybe<Scalars['String']['input']>;
  telegram?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type LandingPageHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
};

export type LandingPageFeaturesItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type LandingPageFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<LandingPageFeaturesItemsMutation>>>;
};

export type LandingPageStatsItemsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type LandingPageStatsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<LandingPageStatsItemsMutation>>>;
};

export type LandingPageTestimonialsItemsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
};

export type LandingPageTestimonialsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<LandingPageTestimonialsItemsMutation>>>;
};

export type LandingPageMutation = {
  hero?: InputMaybe<LandingPageHeroMutation>;
  features?: InputMaybe<LandingPageFeaturesMutation>;
  stats?: InputMaybe<LandingPageStatsMutation>;
  testimonials?: InputMaybe<LandingPageTestimonialsMutation>;
};

export type FooterBrandingMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLinksSectionsItemsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  external?: InputMaybe<Scalars['Boolean']['input']>;
};

export type FooterLinksSectionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<FooterLinksSectionsItemsMutation>>>;
};

export type FooterLinksMutation = {
  sections?: InputMaybe<Array<InputMaybe<FooterLinksSectionsMutation>>>;
};

export type FooterSocialPlatformsMutation = {
  twitter?: InputMaybe<Scalars['String']['input']>;
  discord?: InputMaybe<Scalars['String']['input']>;
  telegram?: InputMaybe<Scalars['String']['input']>;
  youtube?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  github?: InputMaybe<Scalars['String']['input']>;
};

export type FooterSocialMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  platforms?: InputMaybe<FooterSocialPlatformsMutation>;
};

export type FooterNewsletterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLegalLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLegalMutation = {
  copyright?: InputMaybe<Scalars['String']['input']>;
  disclaimer?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<FooterLegalLinksMutation>>>;
};

export type FooterMutation = {
  branding?: InputMaybe<FooterBrandingMutation>;
  links?: InputMaybe<FooterLinksMutation>;
  social?: InputMaybe<FooterSocialMutation>;
  newsletter?: InputMaybe<FooterNewsletterMutation>;
  legal?: InputMaybe<FooterLegalMutation>;
};

export type PublicPageHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
};

export type PublicPageSeoMutation = {
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
};

export type PublicPageMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<PublicPageHeroMutation>;
  content?: InputMaybe<Scalars['JSON']['input']>;
  seo?: InputMaybe<PublicPageSeoMutation>;
};

export type FaqCategoriesQuestionsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['JSON']['input']>;
  tags?: InputMaybe<Scalars['String']['input']>;
};

export type FaqCategoriesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  questions?: InputMaybe<Array<InputMaybe<FaqCategoriesQuestionsMutation>>>;
};

export type FaqMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  categories?: InputMaybe<Array<InputMaybe<FaqCategoriesMutation>>>;
};

export type PricingHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type PricingPlansMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
  popular?: InputMaybe<Scalars['Boolean']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
};

export type PricingMutation = {
  hero?: InputMaybe<PricingHeroMutation>;
  plans?: InputMaybe<Array<InputMaybe<PricingPlansMutation>>>;
};

export type ContactHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type ContactContactInfoMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  businessHours?: InputMaybe<Scalars['String']['input']>;
};

export type ContactFormMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  submitText?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  hero?: InputMaybe<ContactHeroMutation>;
  contactInfo?: InputMaybe<ContactContactInfoMutation>;
  form?: InputMaybe<ContactFormMutation>;
};

export type PostPartsFragment = { __typename: 'Post', title: string, description?: string | null, heroImg?: string | null, date: string, author: string, category?: string | null, tags?: Array<string | null> | null, body?: any | null };

export type PagePartsFragment = { __typename: 'Page', title: string, description?: string | null, body?: any | null };

export type AnnouncementPartsFragment = { __typename: 'Announcement', title: string, message: string, startDate: string, endDate?: string | null, active: boolean, type: string, link?: string | null };

export type TokenPartsFragment = { __typename: 'Token', name: string, symbol: string, description?: string | null, logo: string, contractAddress: string, chain: string, website?: string | null, twitter?: string | null, telegram?: string | null, featured: boolean, order?: number | null };

export type LandingPagePartsFragment = { __typename: 'LandingPage', hero?: { __typename: 'LandingPageHero', title: string, subtitle?: string | null, ctaText: string, ctaLink: string, backgroundImage?: string | null } | null, features?: { __typename: 'LandingPageFeatures', title: string, subtitle?: string | null, items?: Array<{ __typename: 'LandingPageFeaturesItems', title: string, description?: string | null, icon?: string | null, image?: string | null } | null> | null } | null, stats?: { __typename: 'LandingPageStats', title?: string | null, items?: Array<{ __typename: 'LandingPageStatsItems', value: string, label: string, description?: string | null } | null> | null } | null, testimonials?: { __typename: 'LandingPageTestimonials', title?: string | null, items?: Array<{ __typename: 'LandingPageTestimonialsItems', quote: string, author: string, role?: string | null, avatar?: string | null } | null> | null } | null };

export type FooterPartsFragment = { __typename: 'Footer', branding?: { __typename: 'FooterBranding', title: string, subtitle?: string | null, description?: string | null, logo?: string | null } | null, links?: { __typename: 'FooterLinks', sections?: Array<{ __typename: 'FooterLinksSections', title: string, items?: Array<{ __typename: 'FooterLinksSectionsItems', label: string, url: string, external?: boolean | null } | null> | null } | null> | null } | null, social?: { __typename: 'FooterSocial', title?: string | null, description?: string | null, platforms?: { __typename: 'FooterSocialPlatforms', twitter?: string | null, discord?: string | null, telegram?: string | null, youtube?: string | null, linkedin?: string | null, github?: string | null } | null } | null, newsletter?: { __typename: 'FooterNewsletter', title?: string | null, description?: string | null, placeholder?: string | null, buttonText?: string | null } | null, legal?: { __typename: 'FooterLegal', copyright?: string | null, disclaimer?: string | null, links?: Array<{ __typename: 'FooterLegalLinks', label: string, url: string } | null> | null } | null };

export type PublicPagePartsFragment = { __typename: 'PublicPage', slug: string, title: string, description?: string | null, content?: any | null, hero?: { __typename: 'PublicPageHero', title?: string | null, subtitle?: string | null, backgroundImage?: string | null } | null, seo?: { __typename: 'PublicPageSeo', metaTitle?: string | null, metaDescription?: string | null, keywords?: string | null, ogImage?: string | null } | null };

export type FaqPartsFragment = { __typename: 'Faq', title: string, description?: string | null, categories?: Array<{ __typename: 'FaqCategories', name: string, description?: string | null, questions?: Array<{ __typename: 'FaqCategoriesQuestions', question: string, answer: any, tags?: string | null } | null> | null } | null> | null };

export type PricingPartsFragment = { __typename: 'Pricing', hero?: { __typename: 'PricingHero', title: string, subtitle?: string | null } | null, plans?: Array<{ __typename: 'PricingPlans', name: string, description?: string | null, price: string, period?: string | null, features?: Array<string | null> | null, ctaText?: string | null, ctaLink?: string | null, popular?: boolean | null, badge?: string | null } | null> | null };

export type ContactPartsFragment = { __typename: 'Contact', hero?: { __typename: 'ContactHero', title: string, subtitle?: string | null } | null, contactInfo?: { __typename: 'ContactContactInfo', email?: string | null, phone?: string | null, address?: string | null, businessHours?: string | null } | null, form?: { __typename: 'ContactForm', title?: string | null, description?: string | null, submitText?: string | null } | null };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, description?: string | null, heroImg?: string | null, date: string, author: string, category?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, description?: string | null, heroImg?: string | null, date: string, author: string, category?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AnnouncementQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AnnouncementQuery = { __typename?: 'Query', announcement: { __typename: 'Announcement', id: string, title: string, message: string, startDate: string, endDate?: string | null, active: boolean, type: string, link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AnnouncementConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AnnouncementFilter>;
}>;


export type AnnouncementConnectionQuery = { __typename?: 'Query', announcementConnection: { __typename?: 'AnnouncementConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AnnouncementConnectionEdges', cursor: string, node?: { __typename: 'Announcement', id: string, title: string, message: string, startDate: string, endDate?: string | null, active: boolean, type: string, link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TokenQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TokenQuery = { __typename?: 'Query', token: { __typename: 'Token', id: string, name: string, symbol: string, description?: string | null, logo: string, contractAddress: string, chain: string, website?: string | null, twitter?: string | null, telegram?: string | null, featured: boolean, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TokenConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TokenFilter>;
}>;


export type TokenConnectionQuery = { __typename?: 'Query', tokenConnection: { __typename?: 'TokenConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TokenConnectionEdges', cursor: string, node?: { __typename: 'Token', id: string, name: string, symbol: string, description?: string | null, logo: string, contractAddress: string, chain: string, website?: string | null, twitter?: string | null, telegram?: string | null, featured: boolean, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type LandingPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LandingPageQuery = { __typename?: 'Query', landingPage: { __typename: 'LandingPage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'LandingPageHero', title: string, subtitle?: string | null, ctaText: string, ctaLink: string, backgroundImage?: string | null } | null, features?: { __typename: 'LandingPageFeatures', title: string, subtitle?: string | null, items?: Array<{ __typename: 'LandingPageFeaturesItems', title: string, description?: string | null, icon?: string | null, image?: string | null } | null> | null } | null, stats?: { __typename: 'LandingPageStats', title?: string | null, items?: Array<{ __typename: 'LandingPageStatsItems', value: string, label: string, description?: string | null } | null> | null } | null, testimonials?: { __typename: 'LandingPageTestimonials', title?: string | null, items?: Array<{ __typename: 'LandingPageTestimonialsItems', quote: string, author: string, role?: string | null, avatar?: string | null } | null> | null } | null } };

export type LandingPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LandingPageFilter>;
}>;


export type LandingPageConnectionQuery = { __typename?: 'Query', landingPageConnection: { __typename?: 'LandingPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LandingPageConnectionEdges', cursor: string, node?: { __typename: 'LandingPage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'LandingPageHero', title: string, subtitle?: string | null, ctaText: string, ctaLink: string, backgroundImage?: string | null } | null, features?: { __typename: 'LandingPageFeatures', title: string, subtitle?: string | null, items?: Array<{ __typename: 'LandingPageFeaturesItems', title: string, description?: string | null, icon?: string | null, image?: string | null } | null> | null } | null, stats?: { __typename: 'LandingPageStats', title?: string | null, items?: Array<{ __typename: 'LandingPageStatsItems', value: string, label: string, description?: string | null } | null> | null } | null, testimonials?: { __typename: 'LandingPageTestimonials', title?: string | null, items?: Array<{ __typename: 'LandingPageTestimonialsItems', quote: string, author: string, role?: string | null, avatar?: string | null } | null> | null } | null } | null } | null> | null } };

export type FooterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FooterQuery = { __typename?: 'Query', footer: { __typename: 'Footer', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, branding?: { __typename: 'FooterBranding', title: string, subtitle?: string | null, description?: string | null, logo?: string | null } | null, links?: { __typename: 'FooterLinks', sections?: Array<{ __typename: 'FooterLinksSections', title: string, items?: Array<{ __typename: 'FooterLinksSectionsItems', label: string, url: string, external?: boolean | null } | null> | null } | null> | null } | null, social?: { __typename: 'FooterSocial', title?: string | null, description?: string | null, platforms?: { __typename: 'FooterSocialPlatforms', twitter?: string | null, discord?: string | null, telegram?: string | null, youtube?: string | null, linkedin?: string | null, github?: string | null } | null } | null, newsletter?: { __typename: 'FooterNewsletter', title?: string | null, description?: string | null, placeholder?: string | null, buttonText?: string | null } | null, legal?: { __typename: 'FooterLegal', copyright?: string | null, disclaimer?: string | null, links?: Array<{ __typename: 'FooterLegalLinks', label: string, url: string } | null> | null } | null } };

export type FooterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
}>;


export type FooterConnectionQuery = { __typename?: 'Query', footerConnection: { __typename?: 'FooterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FooterConnectionEdges', cursor: string, node?: { __typename: 'Footer', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, branding?: { __typename: 'FooterBranding', title: string, subtitle?: string | null, description?: string | null, logo?: string | null } | null, links?: { __typename: 'FooterLinks', sections?: Array<{ __typename: 'FooterLinksSections', title: string, items?: Array<{ __typename: 'FooterLinksSectionsItems', label: string, url: string, external?: boolean | null } | null> | null } | null> | null } | null, social?: { __typename: 'FooterSocial', title?: string | null, description?: string | null, platforms?: { __typename: 'FooterSocialPlatforms', twitter?: string | null, discord?: string | null, telegram?: string | null, youtube?: string | null, linkedin?: string | null, github?: string | null } | null } | null, newsletter?: { __typename: 'FooterNewsletter', title?: string | null, description?: string | null, placeholder?: string | null, buttonText?: string | null } | null, legal?: { __typename: 'FooterLegal', copyright?: string | null, disclaimer?: string | null, links?: Array<{ __typename: 'FooterLegalLinks', label: string, url: string } | null> | null } | null } | null } | null> | null } };

export type PublicPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PublicPageQuery = { __typename?: 'Query', publicPage: { __typename: 'PublicPage', id: string, slug: string, title: string, description?: string | null, content?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PublicPageHero', title?: string | null, subtitle?: string | null, backgroundImage?: string | null } | null, seo?: { __typename: 'PublicPageSeo', metaTitle?: string | null, metaDescription?: string | null, keywords?: string | null, ogImage?: string | null } | null } };

export type PublicPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicPageFilter>;
}>;


export type PublicPageConnectionQuery = { __typename?: 'Query', publicPageConnection: { __typename?: 'PublicPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PublicPageConnectionEdges', cursor: string, node?: { __typename: 'PublicPage', id: string, slug: string, title: string, description?: string | null, content?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PublicPageHero', title?: string | null, subtitle?: string | null, backgroundImage?: string | null } | null, seo?: { __typename: 'PublicPageSeo', metaTitle?: string | null, metaDescription?: string | null, keywords?: string | null, ogImage?: string | null } | null } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqQuery = { __typename?: 'Query', faq: { __typename: 'Faq', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'FaqCategories', name: string, description?: string | null, questions?: Array<{ __typename: 'FaqCategoriesQuestions', question: string, answer: any, tags?: string | null } | null> | null } | null> | null } };

export type FaqConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
}>;


export type FaqConnectionQuery = { __typename?: 'Query', faqConnection: { __typename?: 'FaqConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqConnectionEdges', cursor: string, node?: { __typename: 'Faq', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'FaqCategories', name: string, description?: string | null, questions?: Array<{ __typename: 'FaqCategoriesQuestions', question: string, answer: any, tags?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type PricingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PricingQuery = { __typename?: 'Query', pricing: { __typename: 'Pricing', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PricingHero', title: string, subtitle?: string | null } | null, plans?: Array<{ __typename: 'PricingPlans', name: string, description?: string | null, price: string, period?: string | null, features?: Array<string | null> | null, ctaText?: string | null, ctaLink?: string | null, popular?: boolean | null, badge?: string | null } | null> | null } };

export type PricingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingFilter>;
}>;


export type PricingConnectionQuery = { __typename?: 'Query', pricingConnection: { __typename?: 'PricingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PricingConnectionEdges', cursor: string, node?: { __typename: 'Pricing', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PricingHero', title: string, subtitle?: string | null } | null, plans?: Array<{ __typename: 'PricingPlans', name: string, description?: string | null, price: string, period?: string | null, features?: Array<string | null> | null, ctaText?: string | null, ctaLink?: string | null, popular?: boolean | null, badge?: string | null } | null> | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactHero', title: string, subtitle?: string | null } | null, contactInfo?: { __typename: 'ContactContactInfo', email?: string | null, phone?: string | null, address?: string | null, businessHours?: string | null } | null, form?: { __typename: 'ContactForm', title?: string | null, description?: string | null, submitText?: string | null } | null } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactHero', title: string, subtitle?: string | null } | null, contactInfo?: { __typename: 'ContactContactInfo', email?: string | null, phone?: string | null, address?: string | null, businessHours?: string | null } | null, form?: { __typename: 'ContactForm', title?: string | null, description?: string | null, submitText?: string | null } | null } | null } | null> | null } };

export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  description
  heroImg
  date
  author
  category
  tags
  body
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  description
  body
}
    `;
export const AnnouncementPartsFragmentDoc = gql`
    fragment AnnouncementParts on Announcement {
  __typename
  title
  message
  startDate
  endDate
  active
  type
  link
}
    `;
export const TokenPartsFragmentDoc = gql`
    fragment TokenParts on Token {
  __typename
  name
  symbol
  description
  logo
  contractAddress
  chain
  website
  twitter
  telegram
  featured
  order
}
    `;
export const LandingPagePartsFragmentDoc = gql`
    fragment LandingPageParts on LandingPage {
  __typename
  hero {
    __typename
    title
    subtitle
    ctaText
    ctaLink
    backgroundImage
  }
  features {
    __typename
    title
    subtitle
    items {
      __typename
      title
      description
      icon
      image
    }
  }
  stats {
    __typename
    title
    items {
      __typename
      value
      label
      description
    }
  }
  testimonials {
    __typename
    title
    items {
      __typename
      quote
      author
      role
      avatar
    }
  }
}
    `;
export const FooterPartsFragmentDoc = gql`
    fragment FooterParts on Footer {
  __typename
  branding {
    __typename
    title
    subtitle
    description
    logo
  }
  links {
    __typename
    sections {
      __typename
      title
      items {
        __typename
        label
        url
        external
      }
    }
  }
  social {
    __typename
    title
    description
    platforms {
      __typename
      twitter
      discord
      telegram
      youtube
      linkedin
      github
    }
  }
  newsletter {
    __typename
    title
    description
    placeholder
    buttonText
  }
  legal {
    __typename
    copyright
    disclaimer
    links {
      __typename
      label
      url
    }
  }
}
    `;
export const PublicPagePartsFragmentDoc = gql`
    fragment PublicPageParts on PublicPage {
  __typename
  slug
  title
  description
  hero {
    __typename
    title
    subtitle
    backgroundImage
  }
  content
  seo {
    __typename
    metaTitle
    metaDescription
    keywords
    ogImage
  }
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  title
  description
  categories {
    __typename
    name
    description
    questions {
      __typename
      question
      answer
      tags
    }
  }
}
    `;
export const PricingPartsFragmentDoc = gql`
    fragment PricingParts on Pricing {
  __typename
  hero {
    __typename
    title
    subtitle
  }
  plans {
    __typename
    name
    description
    price
    period
    features
    ctaText
    ctaLink
    popular
    badge
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  hero {
    __typename
    title
    subtitle
  }
  contactInfo {
    __typename
    email
    phone
    address
    businessHours
  }
  form {
    __typename
    title
    description
    submitText
  }
}
    `;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const AnnouncementDocument = gql`
    query announcement($relativePath: String!) {
  announcement(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AnnouncementParts
  }
}
    ${AnnouncementPartsFragmentDoc}`;
export const AnnouncementConnectionDocument = gql`
    query announcementConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AnnouncementFilter) {
  announcementConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AnnouncementParts
      }
    }
  }
}
    ${AnnouncementPartsFragmentDoc}`;
export const TokenDocument = gql`
    query token($relativePath: String!) {
  token(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TokenParts
  }
}
    ${TokenPartsFragmentDoc}`;
export const TokenConnectionDocument = gql`
    query tokenConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TokenFilter) {
  tokenConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TokenParts
      }
    }
  }
}
    ${TokenPartsFragmentDoc}`;
export const LandingPageDocument = gql`
    query landingPage($relativePath: String!) {
  landingPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LandingPageParts
  }
}
    ${LandingPagePartsFragmentDoc}`;
export const LandingPageConnectionDocument = gql`
    query landingPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LandingPageFilter) {
  landingPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LandingPageParts
      }
    }
  }
}
    ${LandingPagePartsFragmentDoc}`;
export const FooterDocument = gql`
    query footer($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FooterParts
  }
}
    ${FooterPartsFragmentDoc}`;
export const FooterConnectionDocument = gql`
    query footerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FooterFilter) {
  footerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FooterParts
      }
    }
  }
}
    ${FooterPartsFragmentDoc}`;
export const PublicPageDocument = gql`
    query publicPage($relativePath: String!) {
  publicPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PublicPageParts
  }
}
    ${PublicPagePartsFragmentDoc}`;
export const PublicPageConnectionDocument = gql`
    query publicPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PublicPageFilter) {
  publicPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PublicPageParts
      }
    }
  }
}
    ${PublicPagePartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export const PricingDocument = gql`
    query pricing($relativePath: String!) {
  pricing(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PricingParts
  }
}
    ${PricingPartsFragmentDoc}`;
export const PricingConnectionDocument = gql`
    query pricingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PricingFilter) {
  pricingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PricingParts
      }
    }
  }
}
    ${PricingPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    announcement(variables: AnnouncementQueryVariables, options?: C): Promise<{data: AnnouncementQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementQueryVariables, query: string}> {
        return requester<{data: AnnouncementQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementQueryVariables, query: string}, AnnouncementQueryVariables>(AnnouncementDocument, variables, options);
      },
    announcementConnection(variables?: AnnouncementConnectionQueryVariables, options?: C): Promise<{data: AnnouncementConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementConnectionQueryVariables, query: string}> {
        return requester<{data: AnnouncementConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementConnectionQueryVariables, query: string}, AnnouncementConnectionQueryVariables>(AnnouncementConnectionDocument, variables, options);
      },
    token(variables: TokenQueryVariables, options?: C): Promise<{data: TokenQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TokenQueryVariables, query: string}> {
        return requester<{data: TokenQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TokenQueryVariables, query: string}, TokenQueryVariables>(TokenDocument, variables, options);
      },
    tokenConnection(variables?: TokenConnectionQueryVariables, options?: C): Promise<{data: TokenConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TokenConnectionQueryVariables, query: string}> {
        return requester<{data: TokenConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TokenConnectionQueryVariables, query: string}, TokenConnectionQueryVariables>(TokenConnectionDocument, variables, options);
      },
    landingPage(variables: LandingPageQueryVariables, options?: C): Promise<{data: LandingPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingPageQueryVariables, query: string}> {
        return requester<{data: LandingPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingPageQueryVariables, query: string}, LandingPageQueryVariables>(LandingPageDocument, variables, options);
      },
    landingPageConnection(variables?: LandingPageConnectionQueryVariables, options?: C): Promise<{data: LandingPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingPageConnectionQueryVariables, query: string}> {
        return requester<{data: LandingPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingPageConnectionQueryVariables, query: string}, LandingPageConnectionQueryVariables>(LandingPageConnectionDocument, variables, options);
      },
    footer(variables: FooterQueryVariables, options?: C): Promise<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}> {
        return requester<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}, FooterQueryVariables>(FooterDocument, variables, options);
      },
    footerConnection(variables?: FooterConnectionQueryVariables, options?: C): Promise<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}> {
        return requester<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}, FooterConnectionQueryVariables>(FooterConnectionDocument, variables, options);
      },
    publicPage(variables: PublicPageQueryVariables, options?: C): Promise<{data: PublicPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicPageQueryVariables, query: string}> {
        return requester<{data: PublicPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicPageQueryVariables, query: string}, PublicPageQueryVariables>(PublicPageDocument, variables, options);
      },
    publicPageConnection(variables?: PublicPageConnectionQueryVariables, options?: C): Promise<{data: PublicPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicPageConnectionQueryVariables, query: string}> {
        return requester<{data: PublicPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicPageConnectionQueryVariables, query: string}, PublicPageConnectionQueryVariables>(PublicPageConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      },
    pricing(variables: PricingQueryVariables, options?: C): Promise<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}> {
        return requester<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}, PricingQueryVariables>(PricingDocument, variables, options);
      },
    pricingConnection(variables?: PricingConnectionQueryVariables, options?: C): Promise<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}> {
        return requester<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}, PricingConnectionQueryVariables>(PricingConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/1.6/content/875ea65f-9159-4773-857e-d07f66271e14/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  